### ISSUE TITLE
New adonis redis version

### ISSUE THREAD

**Issue by radudalbea** [reg2005/adonis5-cache#5]
Hey,

Could you please update the adonis redis version. The current one 7.0.2. 

At the moment if someone uses the auth module this package can't be installed because of this issue.

The auth module needs the 7th version of redis, you need the 5th.

**Comment by VladyslavP98** [comment]
Could you test update on your project 
` npm i git://github.com/reg2005/adonis5-cache.git#package-update
`

**Comment by radudalbea** [comment]
it's ok. thanks

**Comment by mastermunj** [comment]
@VladyslavParashchenko is any release planned for this update?

**Comment by VladyslavP98** [comment]
@reg2005 , could you publish new version on npm ?

**Comment by reg2005** [comment]
The package has been updated. Please check it

**Comment by radudalbea** [comment]
fixed
